In [1]:
import pandas as pd


data = {
    'الاسم': ['أحمد', 'فاطمة', 'محمد', 'سارة', 'خالد'],
    'العمر': [25, 30, 22, 28, 35],
    'المدينة': ['صنعاء', 'عدن', 'تعز', 'إب', 'الحديدة'],
    'الدرجة': [85, 90, 78, 92, 88]
}

In [2]:
df = pd.DataFrame(data)

print("عينة من البيانات:")
display(df.head())

عينة من البيانات:

   الاسم  العمر  المدينة  الدرجة
0   أحمد     25    صنعاء      85
1  فاطمة     30      عدن      90
2   محمد     22      تعز      78
3   سارة     28       إب      92
4   خالد     35  الحديدة      88

In [ ]:

print("معلومات البيانات:")
df.info()

In [ ]:
print("الإحصائيات الوصفية:")
display(df.describe())

In [3]:

df_filtered = df[df['الدرجة'] > 80]


print("عدد الصفوف والأعمدة بعد التصفية:")
print(df_filtered.shape)

عدد الصفوف والأعمدة بعد التصفية:
(4, 4)

In [4]:
print("البيانات بعد التصفية:")
display(df_filtered)

البيانات بعد التصفية:

   الاسم  العمر  المدينة  الدرجة
0   أحمد     25    صنعاء      85
1  فاطمة     30      عدن      90
3   سارة     28       إب      92
4   خالد     35  الحديدة      88